spring:
  datasource:
    url: jdbc:h2:mem:finance
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true # resource/*.sql 파일을 자동으로 넣어주는 옵션 
    database-platform: H2
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": true

  redis:
    host: localhost
    port: 16379

scheduler:
  scrap:
    yahoo: 0 0 0 * * *
